### ISSUE TITLE
Date Picker Style

### ISSUE THREAD

**Issue by Sebas37** [BlackBoxVision/datetimepicker-edittext#1]
Hi, thanks for your awesome lib.
 I would like can show an custom datePicker, change colors, etc.

You are amazing (we, que le pasaba)

**Comment by JonatanSalas** [comment]
Hi @Sebas37, this is now supported with this commit https://github.com/BlackBoxVision/datetimepicker-edittext/commit/b82d33ff85d06265549ee528fb44ddd215da388a. I have added a new attribute **theme** where you pass a reference to a custom style.

**Comment by JonatanSalas** [comment]
This should be added in v0.3.0
