### ISSUE TITLE
how do I get the date from DatePickerEditText and set the date in a textView ??

### ISSUE THREAD

**Issue by Shanto16** [BlackBoxVision/datetimepicker-edittext#10]
I want to show the date that I selected from DatePickerEditText to show on a text view. How do I do that ??

**Comment by JonatanSalas** [comment]
@Shanto16  DatePickerEditText it's a simple EditText, so you can take the value when you want: 

e.g:
```java 
datePickerEditText.getTexT().toString();
//or
datePickerEditText.getDate();
```

**Comment by JonatanSalas** [comment]
@Shanto16 I will close the issue. Let me know if you need something else, or re-open it!
