### ISSUE TITLE
unable to resolve with android latest version

### ISSUE THREAD

**Issue by microcian** [BlackBoxVision/datetimepicker-edittext#11]
hi, i've updated my app and getting error after upgrading from 25 to 26, please help me to sort out this issue

compileSdkVersion 26
buildToolsVersion "26.0.1"

![untitled](https://user-images.githubusercontent.com/4646811/30404189-e046ab48-98fe-11e7-8441-1aab4762348c.png)

**Comment by JonatanSalas** [comment]
@abdulrahmanmajeed it seems to be a trouble related to dependency resolution for what I can see. 

Have you added `jitpack config` in your project `build.gradle`? 

You should do in this way:

```gradle
allprojects {
    repositories {
        ...
        maven { 
	    url "https://jitpack.io" 
        }
    }
}
```

Let me know if it helps you!

**Comment by gulsanobermemon** [comment]
Can you please increase the min date Limit. I want it 100 years back from today.

**Comment by microcian** [comment]
Thanks man ..resolved !! ..you may close issue

**Comment by JonatanSalas** [comment]
@gulsanobermemon please, open a new issue so I can close this one. Today at night, I will implement support for custom date setting.

**Comment by JonatanSalas** [comment]
@abdulrahmanmajeed you're welcome! Glad to help you!
