### ISSUE TITLE
Dialog showing when changing visibiity

### ISSUE THREAD

**Issue by kix2902** [BlackBoxVision/datetimepicker-edittext#5]
I have a layout with 3 DatePickerEditText and when I change its visibility between VISIBLE and GONE a pair of times the picker dialog appears many times.

**Comment by kix2902** [comment]
I've tested it another time and it appears even with the first call to setVisibility(View.GONE) of the DatePickerEditText.

**Comment by JonatanSalas** [comment]
@kix2902 would you mind to show me an example repo? So I can test this and check better!

**Comment by kix2902** [comment]
Sorry, it's a private project... but it's easily testable, just create a layout with a DatePickerEditText and a Button to change the visibility of the DatePickerEditText, click on it a pair of times and it will appear the dialog to pick a date.

**Comment by JonatanSalas** [comment]
@kix2902 hey, no trouble! Thank you for give to me the steps in order to reproduce the issue.

**Comment by JonatanSalas** [comment]
@kix2902 I have tested it, what you're saying is true. I will work on it, and I guess, in a few hours I will have a fix for it!

**Comment by JonatanSalas** [comment]
@kix2902 I will upload a commit and release a new version in a few minutes.

**Comment by kix2902** [comment]
Thank you very much ;D

**Comment by JonatanSalas** [comment]
@kix2902 test release version v0.3.2! and let me know so I can close this issue or review it! 😄

**Comment by kix2902** [comment]
It keeps failing (the second time only) and now it's necessary to click on it two times to open the dialog.

**Comment by JonatanSalas** [comment]
@kix2902 two times? Are you sure? In which android version are you running your app? I need to know some further details. 

I have tested in my API 23 Android Emulator and it works as expected. 😞

**Comment by kix2902** [comment]
Yes, one to capture the focus and another to open the datepicker.
This afternoon I'll try to make some test and send you a PR or a sample app.

**Comment by kix2902** [comment]
I retried now 3.0.2 version and it seems to work correctly, maybe a bug with Gradle's cache system...

**Comment by JonatanSalas** [comment]
Great! I will close the issue now, but if you need something else related to this issue, consider re open it!
