### ISSUE TITLE
timePickerEditText.setTime(now); doesn't work?

### ISSUE THREAD

**Issue by Xorok** [BlackBoxVision/datetimepicker-edittext#8]
I'm using DatePickerEditText as well as TimePickerEditText in a dialog, and want to set the default time as the current time. While it works for the first DatePickerEditText, calling timePickerEditText.setTime(now); does nothing. The EditText stays empty, timePickerEditText.getTime(); returns null.

```
    @NonNull
    @Override
    public AlertDialog onCreateDialog(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
        // Get the layout inflater
        LayoutInflater inflater = getActivity().getLayoutInflater();

        // Inflate and set the layout for the dialog
        // Pass null as the parent view because its going in the dialog layout
        View view = inflater.inflate(R.layout.fragment_dialog_add, null);
        unbinder = ButterKnife.bind(this, view);

        Calendar now = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy", Locale.GERMAN);

        datePickerEditText.setManager(getFragmentManager());
        datePickerEditText.setMaxDate(sdf.format(now.getTime()));
        datePickerEditText.setDate(now);
        timePickerEditText.setManager(getFragmentManager());
        timePickerEditText.setTime(now); // TODO: File bug on GitHub

        builder.setView(view)
                // Add action buttons
                .setPositiveButton("OK", (dialog, id) -> {
                    ...
                })
                .setNegativeButton("CANCEL", (dialog, id) ->
                    ...
                );

        return builder.create();
    }
```

**Comment by JonatanSalas** [comment]
@Xorok Thank you for reporting it. I will try to review today this bug.

**Comment by JonatanSalas** [comment]
@Xorok I have updated the example App. Would you mind to checkout this repo and give a try to the sample? It's currently working for me, also, the current codebase it's not released yet because I have recently migrated it to Kotlin. 

Please, give it a try and let me know if the repo app works for you.

**Comment by JonatanSalas** [comment]
@Xorok Let me know if your issue it's been solved.

**Comment by Xorok** [comment]
Hello,
unfortunately I have since used Android's regular date & time pickers and won't be able to report back. You can see this issue as resolved and close it.

**Comment by JonatanSalas** [comment]
@xorok ok! thank you!
