### ISSUE TITLE
Datepicker not selecting today's date on android VR: 5.1.1

### ISSUE THREAD

**Issue by AliAzaz** [BlackBoxVision/datetimepicker-edittext#9]
Hi.
I've used this date picker and its working fine on most of the devices but when I implement this library on android VR:5.1.1 and set max date to current date and run it, it shows the pointer on current date but if by mistake I select the different date and wants to re-select the current date it's can't. 
Screenshot attached.
![screenshot_2017-06-21-09-20-39 1](https://user-images.githubusercontent.com/12116478/27368019-95a47b06-5669-11e7-9e04-d340c7fd54d5.png)

**Comment by JonatanSalas** [comment]
Hi @AliAzaz! Would you mind to show me a code snippet? So, I can reproduce better your issue. 
Thanks!

**Comment by AliAzaz** [comment]
Simply I did this:

`DatePickerEditText datePickerEditText = (DatePickerEditText) findViewById(R.id.datePickerEditText);
datePickerEditText.setManager(getSupportFragmentManager());

String dateToday = new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTimeInMillis());
datePickerEditText.setMaxDate(dateToday);`

**Comment by JonatanSalas** [comment]
This's issue is because you're using wrong the setMaxDate field. The setMaxDate, will set the maxDate property on the DatePicker, so, by default it will show the current date marked, but, if you perform a click event over it, it won't work . I will see how to figure this out.

**Comment by JonatanSalas** [comment]
Excuse me for the long delay, I have been inactive for a while!
